events{
    #defines the maximum number of simultaneous connections that can be opened by a worker process
    worker_connections 1024;
}

http{

    #Includes the type of files(css,js,images) so the website can be displayed correctly
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server{
        #Only Ivp4 in port 443 with ssl
        listen 443 ssl;

        listen [::]:443 ssl;

        server_name ${DOMAIN_NAME};

        #Path do the certificate and key
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        #We can only use TLSv1 1.2 or TLSv1.3 
        ssl_protocols TLSv1.2 TLSv1.3;

        #Files of the website
        root /var/www/html/;

        #Defines the index files of the website
        index index.php index.html index.htm;

        #Try to find the file requested by the user
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            #File that handles stantard php config
            include snippets/fastcgi-php.conf;

            #Passes the request to the wordpress container on port 9000
            fastcgi_pass wordpress:9000;
        }
    }
}